@url = http://localhost:5000

# GET {{MySpot_HostAddress}}/weatherforecast/
# Accept: application/json

###

GET {{url}}

###
GET {{url}}/reservations

###
POST {{url}}/reservations
Content-Type: application/json
{
  "employeeName" : "John Doe",
  "parkingSpotName": "P1",
  "LicensePlate": "ZK2343",
}

###
PUT {{url}}/reservations